name: Flutter Automated Tests

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    name: Run Flutter Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'
          channel: 'stable'

      - name: Instalar dependências
        run: flutter pub get

      - name: Executar testes automatizados
        run: flutter test --coverage

      - name: Instalar LCOV
        run: sudo apt-get update && sudo apt-get install -y lcov

      - name: Gerar relatório HTML de cobertura
        run: genhtml coverage/lcov.info -o coverage/html

      - name: Publicar relatório de cobertura como artefato
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/html